server:
  port: 8089
  tomcat:
    relaxed-query-chars: '|,{,},[,]'
#postgre
spring:
  datasource:
    url: jdbc:postgresql://postgresql-dev.postgresql.svc.cluster.local:5432/invoice
    username: testadmin
    password: testadmin123
    
  jpa:
    open-in-view: true
 
#  datasource:
#    url: jdbc:postgresql://localhost:5432/invoice
#    username: postgres
#    password: root
#  jackson:
#      parser:
#        allow-numeric-leading-zeros: true


  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update
#    show-sql: true
